CREATE TABLE ACTIVITY_OWNER.TAPEX_AUTOMATION_LOG
(
  ID                      NUMBER,
  WORKSPACE_ID            NUMBER                NOT NULL,
  WORKSPACE_NAME          VARCHAR2(255 BYTE)    NOT NULL,
  WORKSPACE_DISPLAY_NAME  VARCHAR2(4000 BYTE),
  APPLICATION_ID          NUMBER,
  AUTOMATION_ID           NUMBER,
  AUTOMATION_NAME         VARCHAR2(255 BYTE),
  IS_JOB                  VARCHAR2(3 BYTE),
  STATUS_CODE             VARCHAR2(19 BYTE),
  STATUS                  VARCHAR2(32 BYTE),
  START_TIMESTAMP         TIMESTAMP(6) WITH TIME ZONE,
  END_TIMESTAMP           TIMESTAMP(6) WITH TIME ZONE,
  SUCCESSFUL_ROW_COUNT    NUMBER,
  ERROR_ROW_COUNT         NUMBER
)
TABLESPACE ACTIVITY_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE TABLE ACTIVITY_OWNER.TAPEX_DEBUG_MESSAGES
(
  ID                 NUMBER,
  PAGE_VIEW_ID       NUMBER,
  MESSAGE_TIMESTAMP  TIMESTAMP(6),
  ELAPSED_TIME       NUMBER,
  EXECUTION_TIME     NUMBER,
  MESSAGE            VARCHAR2(4000 BYTE),
  APPLICATION_ID     NUMBER,
  PAGE_ID            NUMBER,
  SESSION_ID         NUMBER,
  APEX_USER          VARCHAR2(255 BYTE),
  MESSAGE_LEVEL      NUMBER,
  WORKSPACE_ID       NUMBER,
  CALL_STACK         VARCHAR2(4000 BYTE),
  CREATED_BY         VARCHAR2(20 BYTE),
  CREATED_DATE       DATE,
  MODIFIED_BY        VARCHAR2(20 BYTE),
  MODIFIED_DATE      DATE
)
TABLESPACE ACTIVITY_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE TABLE ACTIVITY_OWNER.TAPEX_MAIL_LOG
(
  MAIL_ID                  NUMBER,
  MAIL_MESSAGE_ID          VARCHAR2(4000 BYTE),
  MAIL_TO                  VARCHAR2(4000 BYTE),
  MAIL_FROM                VARCHAR2(4000 BYTE),
  MAIL_REPLYTO             VARCHAR2(4000 BYTE),
  MAIL_SUBJ                VARCHAR2(4000 BYTE),
  MAIL_CC                  VARCHAR2(4000 BYTE),
  MAIL_BCC                 VARCHAR2(4000 BYTE),
  MAIL_MESSAGE_CREATED     DATE,
  MAIL_MESSAGE_SEND_BEGIN  DATE,
  MAIL_MESSAGE_SEND_END    DATE,
  MAIL_BODY_SIZE           NUMBER,
  MAIL_BODY_HTML_SIZE      NUMBER,
  MAIL_ATTACHMENT_COUNT    NUMBER,
  MAIL_ATTACHMENT_SIZE     NUMBER,
  MAIL_SEND_ERROR          VARCHAR2(4000 BYTE),
  LAST_UPDATED_ON          DATE,
  APP_ID                   NUMBER,
  WORKSPACE_ID             NUMBER               NOT NULL,
  WORKSPACE_NAME           VARCHAR2(255 BYTE)   NOT NULL
)
TABLESPACE ACTIVITY_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE TABLE ACTIVITY_OWNER.TAPEX_MAIL_QUEUE
(
  ID                       NUMBER,
  MAIL_TO                  VARCHAR2(4000 BYTE),
  MAIL_FROM                VARCHAR2(4000 BYTE),
  MAIL_REPLYTO             VARCHAR2(4000 BYTE),
  MAIL_SUBJ                VARCHAR2(4000 BYTE),
  MAIL_CC                  VARCHAR2(4000 BYTE),
  MAIL_BCC                 VARCHAR2(4000 BYTE),
  MAIL_BODY                CLOB,
  MAIL_BODY_HTML           CLOB,
  MAIL_SEND_COUNT          NUMBER(2),
  MAIL_SEND_ERROR          VARCHAR2(4000 BYTE),
  LAST_UPDATED_BY          VARCHAR2(255 BYTE),
  LAST_UPDATED_ON          DATE,
  MAIL_MESSAGE_CREATED     DATE,
  MAIL_MESSAGE_CREATED_BY  VARCHAR2(255 BYTE),
  APP_ID                   NUMBER,
  WORKSPACE_ID             NUMBER               NOT NULL,
  WORKSPACE_NAME           VARCHAR2(255 BYTE)   NOT NULL
)
LOB (MAIL_BODY) STORE AS SECUREFILE (
  TABLESPACE  ACTIVITY_DATA
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
LOB (MAIL_BODY_HTML) STORE AS SECUREFILE (
  TABLESPACE  ACTIVITY_DATA
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE ACTIVITY_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE TABLE ACTIVITY_OWNER.TAPEX_WORKSPACE_ACCESS_LOG
(
  WORKSPACE                 VARCHAR2(255 BYTE)  NOT NULL,
  WORKSPACE_DISPLAY_NAME    VARCHAR2(4000 BYTE),
  APPLICATION_ID            NUMBER,
  APPLICATION_NAME          VARCHAR2(255 BYTE),
  USER_NAME                 VARCHAR2(255 BYTE),
  AUTHENTICATION_METHOD     VARCHAR2(255 BYTE),
  APPLICATION_SCHEMA_OWNER  VARCHAR2(255 BYTE),
  ACCESS_DATE               DATE,
  SECONDS_AGO               NUMBER,
  IP_ADDRESS                VARCHAR2(255 BYTE),
  AUTHENTICATION_RESULT     VARCHAR2(40 BYTE),
  CUSTOM_STATUS_TEXT        VARCHAR2(4000 BYTE),
  WORKSPACE_ID              NUMBER,
  CREATED_BY                VARCHAR2(20 BYTE),
  CREATED_DATE              DATE,
  MODIFIED_BY               VARCHAR2(20 BYTE),
  MODIFIED_DATE             DATE
)
TABLESPACE ACTIVITY_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE TABLE ACTIVITY_OWNER.TAPEX_WORKSPACE_ACTIVITY_LOG
(
  WORKSPACE                 VARCHAR2(255 BYTE),
  WORKSPACE_DISPLAY_NAME    VARCHAR2(4000 BYTE),
  APEX_USER                 VARCHAR2(255 BYTE),
  APPLICATION_ID            NUMBER,
  APPLICATION_NAME          VARCHAR2(255 BYTE),
  APPLICATION_SCHEMA_OWNER  VARCHAR2(128 BYTE),
  PAGE_ID                   NUMBER,
  PAGE_NAME                 VARCHAR2(255 BYTE),
  VIEW_DATE                 DATE,
  THINK_TIME                NUMBER,
  SECONDS_AGO               NUMBER,
  LOG_CONTEXT               VARCHAR2(255 BYTE),
  ELAPSED_TIME              NUMBER,
  ROWS_QUERIED              NUMBER,
  IP_ADDRESS                VARCHAR2(4000 BYTE),
  AGENT                     VARCHAR2(4000 BYTE),
  APEX_SESSION_ID           NUMBER,
  APPLICATION_TENANT_ID     VARCHAR2(32 BYTE),
  ERROR_MESSAGE             VARCHAR2(4000 BYTE),
  ERROR_ON_COMPONENT_TYPE   VARCHAR2(255 BYTE),
  ERROR_ON_COMPONENT_NAME   VARCHAR2(255 BYTE),
  PAGE_VIEW_MODE            VARCHAR2(15 BYTE),
  APPLICATION_INFO          VARCHAR2(10 BYTE),
  INTERACTIVE_REPORT_ID     NUMBER,
  IR_SAVED_REPORT_ID        NUMBER,
  IR_SEARCH                 VARCHAR2(4000 BYTE),
  WS_APPLICATION_ID         NUMBER,
  WS_PAGE_ID                NUMBER,
  WS_DATAGRID_ID            NUMBER,
  CONTENT_LENGTH            NUMBER,
  REGIONS_FROM_CACHE        NUMBER,
  WORKSPACE_ID              NUMBER,
  PAGE_VIEW_TYPE            VARCHAR2(23 BYTE),
  REQUEST_VALUE             VARCHAR2(4000 BYTE),
  DEBUG_PAGE_VIEW_ID        NUMBER,
  VIEW_TIMESTAMP            TIMESTAMP(6),
  ECID                      VARCHAR2(64 BYTE),
  CREATED_BY                VARCHAR2(20 BYTE),
  CREATED_DATE              DATE,
  MODIFIED_BY               VARCHAR2(20 BYTE),
  MODIFIED_DATE             DATE
)
TABLESPACE ACTIVITY_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE INDEX ACTIVITY_OWNER.INDS_DEBUG_ID ON ACTIVITY_OWNER.TAPEX_DEBUG_MESSAGES
(ID)
LOGGING
TABLESPACE ACTIVITY_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX ACTIVITY_OWNER.INDX_APP_ID ON ACTIVITY_OWNER.TAPEX_WORKSPACE_ACTIVITY_LOG
(APPLICATION_ID)
LOGGING
TABLESPACE ACTIVITY_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX ACTIVITY_OWNER.INDX_APP_NAME ON ACTIVITY_OWNER.TAPEX_WORKSPACE_ACTIVITY_LOG
(APPLICATION_NAME)
LOGGING
TABLESPACE ACTIVITY_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX ACTIVITY_OWNER.INDX_DEBUG_APEX_USER ON ACTIVITY_OWNER.TAPEX_DEBUG_MESSAGES
(APEX_USER)
LOGGING
TABLESPACE ACTIVITY_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX ACTIVITY_OWNER.INDX_DEBUG_APP_ID ON ACTIVITY_OWNER.TAPEX_DEBUG_MESSAGES
(APPLICATION_ID)
LOGGING
TABLESPACE ACTIVITY_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX ACTIVITY_OWNER.INDX_DEBUG_WS_ID ON ACTIVITY_OWNER.TAPEX_DEBUG_MESSAGES
(WORKSPACE_ID)
LOGGING
TABLESPACE ACTIVITY_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX ACTIVITY_OWNER.INDX_MAIL_APP_ID ON ACTIVITY_OWNER.TAPEX_MAIL_LOG
(APP_ID)
LOGGING
TABLESPACE ACTIVITY_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX ACTIVITY_OWNER.INDX_MAIL_ID ON ACTIVITY_OWNER.TAPEX_MAIL_LOG
(MAIL_ID)
LOGGING
TABLESPACE ACTIVITY_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX ACTIVITY_OWNER.INDX_VIEW_DATE ON ACTIVITY_OWNER.TAPEX_WORKSPACE_ACTIVITY_LOG
(VIEW_DATE)
LOGGING
TABLESPACE ACTIVITY_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX ACTIVITY_OWNER.INDX_WS_NAME ON ACTIVITY_OWNER.TAPEX_MAIL_LOG
(WORKSPACE_NAME)
LOGGING
TABLESPACE ACTIVITY_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
